


















.build/WiShield/uip-split.o : lib/WiShield/uip-split.c
	@echo [93mWiShield/uip-split.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/uip-split.c
include .build/WiShield/uip-split.d

.build/WiShield/network.o : lib/WiShield/network.c
	@echo [93mWiShield/network.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/network.c
include .build/WiShield/network.d

.build/WiShield/strings.o : lib/WiShield/strings.c
	@echo [93mWiShield/strings.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/strings.c
include .build/WiShield/strings.d

.build/WiShield/uip_dns.o : lib/WiShield/uip_dns.c
	@echo [93mWiShield/uip_dns.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/uip_dns.c
include .build/WiShield/uip_dns.d

.build/WiShield/uip.o : lib/WiShield/uip.c
	@echo [93mWiShield/uip.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/uip.c
include .build/WiShield/uip.d

.build/WiShield/uip_dhcp.o : lib/WiShield/uip_dhcp.c
	@echo [93mWiShield/uip_dhcp.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/uip_dhcp.c
include .build/WiShield/uip_dhcp.d

.build/WiShield/stack.o : lib/WiShield/stack.c
	@echo [93mWiShield/stack.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/stack.c
include .build/WiShield/stack.d

.build/WiShield/g2100.o : lib/WiShield/g2100.c
	@echo [93mWiShield/g2100.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/g2100.c
include .build/WiShield/g2100.d

.build/WiShield/clock-arch.o : lib/WiShield/clock-arch.c
	@echo [93mWiShield/clock-arch.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/clock-arch.c
include .build/WiShield/clock-arch.d

.build/WiShield/uip-neighbor.o : lib/WiShield/uip-neighbor.c
	@echo [93mWiShield/uip-neighbor.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/uip-neighbor.c
include .build/WiShield/uip-neighbor.d

.build/WiShield/uip_arp.o : lib/WiShield/uip_arp.c
	@echo [93mWiShield/uip_arp.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/uip_arp.c
include .build/WiShield/uip_arp.d

.build/WiShield/uip-fw.o : lib/WiShield/uip-fw.c
	@echo [93mWiShield/uip-fw.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/uip-fw.c
include .build/WiShield/uip-fw.d

.build/WiShield/uiplib.o : lib/WiShield/uiplib.c
	@echo [93mWiShield/uiplib.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/uiplib.c
include .build/WiShield/uiplib.d

.build/WiShield/memb.o : lib/WiShield/memb.c
	@echo [93mWiShield/memb.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/memb.c
include .build/WiShield/memb.d

.build/WiShield/timer.o : lib/WiShield/timer.c
	@echo [93mWiShield/timer.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/timer.c
include .build/WiShield/timer.d

.build/WiShield/psock.o : lib/WiShield/psock.c
	@echo [93mWiShield/psock.c[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c lib/WiShield/psock.c
include .build/WiShield/psock.d






.build/WiShield/WiShield.o : lib/WiShield/WiShield.cpp
	@echo [93mWiShield/WiShield.cpp[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/WiShield/WiShield.cpp
include .build/WiShield/WiShield.d

.build/WiShield/request.o : lib/WiShield/request.cpp
	@echo [93mWiShield/request.cpp[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/WiShield/request.cpp
include .build/WiShield/request.d

.build/WiShield/WiServer.o : lib/WiShield/WiServer.cpp
	@echo [93mWiShield/WiServer.cpp[0m
	@mkdir -p .build/WiShield
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/WiShield/WiServer.cpp
include .build/WiShield/WiServer.d



.build/WiShield/libWiShield.a : .build/WiShield/uip-split.o .build/WiShield/network.o .build/WiShield/strings.o .build/WiShield/uip_dns.o .build/WiShield/uip.o .build/WiShield/uip_dhcp.o .build/WiShield/stack.o .build/WiShield/g2100.o .build/WiShield/clock-arch.o .build/WiShield/uip-neighbor.o .build/WiShield/uip_arp.o .build/WiShield/uip-fw.o .build/WiShield/uiplib.o .build/WiShield/memb.o .build/WiShield/timer.o .build/WiShield/psock.o .build/WiShield/WiShield.o .build/WiShield/request.o .build/WiShield/WiServer.o
	@echo [92mLinking libWiShield.a[0m
	@/usr/bin/avr-ar rcs $@ $^







.build/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
include .build/arduino/WInterrupts.d

.build/arduino/wiring.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
include .build/arduino/wiring.d

.build/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
include .build/arduino/wiring_digital.d

.build/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
include .build/arduino/wiring_shift.d

.build/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/arduino/wiring_pulse.d

.build/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
include .build/arduino/wiring_analog.d






.build/arduino/main.o : /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
include .build/arduino/main.d

.build/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
include .build/arduino/USBCore.d

.build/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/arduino/IPAddress.d

.build/arduino/Tone.o : /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
include .build/arduino/Tone.d

.build/arduino/HID.o : /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
include .build/arduino/HID.d

.build/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/arduino/HardwareSerial.d

.build/arduino/CDC.o : /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
include .build/arduino/CDC.d

.build/arduino/Print.o : /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
include .build/arduino/Print.d

.build/arduino/new.o : /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
include .build/arduino/new.d

.build/arduino/WMath.o : /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
include .build/arduino/WMath.d

.build/arduino/WString.o : /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
include .build/arduino/WString.d

.build/arduino/Stream.o : /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
include .build/arduino/Stream.d



.build/arduino/libarduino.a : .build/arduino/WInterrupts.o .build/arduino/wiring.o .build/arduino/wiring_digital.o .build/arduino/wiring_shift.o .build/arduino/wiring_pulse.o .build/arduino/wiring_analog.o .build/arduino/main.o .build/arduino/USBCore.o .build/arduino/IPAddress.o .build/arduino/Tone.o .build/arduino/HID.o .build/arduino/HardwareSerial.o .build/arduino/CDC.o .build/arduino/Print.o .build/arduino/new.o .build/arduino/WMath.o .build/arduino/WString.o .build/arduino/Stream.o
	@echo [92mLinking libarduino.a[0m
	@/usr/bin/avr-ar rcs $@ $^







.build/src/webclient.o : src/webclient.c
	@echo [93msrc/webclient.c[0m
	@mkdir -p .build/src
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino  -o $@ -c src/webclient.c
include .build/src/webclient.d









.build/src/AiloveBox.o : .build/src/AiloveBox.cpp
	@echo [93msrc/AiloveBox.cpp[0m
	@mkdir -p .build/src
	@/usr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/WiShield -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build/src/AiloveBox.cpp
include .build/src/AiloveBox.d







.build/firmware.elf : .build/src/webclient.o .build/src/AiloveBox.o .build/WiShield/libWiShield.a .build/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/bin/avr-gcc -Os -Wl,--gc-sections -mmcu=atmega328p -o $@ $^ -lm


.build/firmware.hex : .build/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/src/dependencies.d .build/arduino/dependencies.d .build/WiShield/dependencies.d

all : .build/firmware.hex
	@true

