







	



.build/WiShield/WiShield.d : lib/WiShield/WiShield.cpp
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/WiShield.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/uip-split.d : lib/WiShield/uip-split.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/uip-split.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/network.d : lib/WiShield/network.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/network.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/strings.d : lib/WiShield/strings.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/strings.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/uip_dns.d : lib/WiShield/uip_dns.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/uip_dns.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/uip.d : lib/WiShield/uip.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/uip.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/uip_dhcp.d : lib/WiShield/uip_dhcp.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/uip_dhcp.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/stack.d : lib/WiShield/stack.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/stack.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/g2100.d : lib/WiShield/g2100.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/g2100.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/clock-arch.d : lib/WiShield/clock-arch.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/clock-arch.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/uip-neighbor.d : lib/WiShield/uip-neighbor.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/uip-neighbor.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/uip_arp.d : lib/WiShield/uip_arp.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/uip_arp.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/uip-fw.d : lib/WiShield/uip-fw.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/uip-fw.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/uiplib.d : lib/WiShield/uiplib.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/uiplib.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/request.d : lib/WiShield/request.cpp
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/request.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/memb.d : lib/WiShield/memb.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/memb.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/timer.d : lib/WiShield/timer.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/timer.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/WiServer.d : lib/WiShield/WiServer.cpp
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/WiServer.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@

.build/WiShield/psock.d : lib/WiShield/psock.c
	@mkdir -p .build/WiShield
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/WiShield -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility  -MM $^ > $@
	
	@printf ".build/WiShield/psock.d .build/WiShield/" | cat - $@ > $@~ && mv $@~ $@



.build/WiShield/dependencies.d : .build/WiShield/WiShield.d .build/WiShield/uip-split.d .build/WiShield/network.d .build/WiShield/strings.d .build/WiShield/uip_dns.d .build/WiShield/uip.d .build/WiShield/uip_dhcp.d .build/WiShield/stack.d .build/WiShield/g2100.d .build/WiShield/clock-arch.d .build/WiShield/uip-neighbor.d .build/WiShield/uip_arp.d .build/WiShield/uip-fw.d .build/WiShield/uiplib.d .build/WiShield/request.d .build/WiShield/memb.d .build/WiShield/timer.d .build/WiShield/WiServer.d .build/WiShield/psock.d
	@echo [96mScanning dependencies of WiShield[0m
	@mkdir -p .build/WiShield
	@cat $^ > $@;

all : .build/WiShield/dependencies.d
	@true

